app:
  env: 'local'
  debug: true
  addr: ':8080'


mysql:
  host: '127.0.0.1'
  port: '3306'
  database: 'ah'
  username: 'root'
  password: ''
  max-idle-conns: 10
  max-open-conns: 100

zap:
  level: 'info'
  format: 'console'
  prefix: '[server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true