app:
  env: 'dev'
  debug: true
  addr: ':8080'


mysql:
  host: '127.0.0.1'
  port: '3306'
  database: 'ah'
  username: 'root'
  password: ''
  max-idle-conns: 10
  max-open-conns: 100

redis:
  host: '127.0.0.1'
  port: '6379'
  username: ''
  password: ''
  db: 0

zap:
  level: 'info'
  format: 'console'
  prefix: '[server]'
  directory: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false